### ISSUE TITLE
wireless terminal

### ISSUE THREAD

**Issue by kitorer** [purduesigbots/pros-cli#122] opened 2020-01-23 14:09 UTC
Adding the capability to open the terminal while plugged into the controller

**Comment by nathan-moore** [comment] 2020-01-23 14:19
Duplicate of https://github.com/purduesigbots/pros-cli/issues/94. If you check the prs, receiving is well on its way, with sending to the robot not there yet. We don't really have an estimate when this will be released though.

**Closed as completed by nathan-moore** 2020-01-23 14:19 UTC
