### ISSUE TITLE
Problems reading or writing with ifstream

### ISSUE THREAD

**Issue by sealj553** [purduesigbots/pros-cli#33] opened 2018-10-23 22:25 UTC
I've been working with some code which uses `std::ifstream` to manipulate files, and it can open the files, but cannot read or write. `tellg` seems to always return -1. I can convert it to use `fopen` and `fread` and it works perfectly. I've had to do this for multiple projects, so it seems like a problem with PROS.

I can provide a code sample if needed.

**Comment by HotelCalifornia** [comment] 2018-12-20 15:22
going to close as a duplicate of #18

**Closed as completed by HotelCalifornia** 2018-12-20 15:22 UTC
